### PR TITLE
Update sys_port.i for ESP8266 for timing

### PR DESCRIPTION
**Pull request by rahuldeo2047**
Update sys_port.i for nanosecond in sys_port_get_time_into_tick()
The (micros * 1000) for now.

### CODE REVIEW

**Comment by rahuldeo2047** [comment]
Loosely related to https://github.com/eerimoq/simba/issues/155

**Comment by eerimoq** [comment]
Will this give the correct time into the tick? I doubt it since the time source for the ESP system time and the Simba system tick are likely not synchronized.

**Comment by rahuldeo2047** [comment]
Thank you for the response.

I'll understand the sync requirement. Are you thinking about the locks (sys_lock()) or something else?
However, in applications' perspective ultrasonic is working and MPU-IMU is not. Wifi tcp data received by host ubuntu PC is also jittery.  Reference: [wip](https://github.com/rahuldeo2047/ESP_rtos_eval/tree/5defab26d13b5fa05d1b7ca2fb97fb094019f4fc/simba/i2c/sensors)

I'll be back with a gpio to oscilloscope timing comparison. If I have access to an oscilloscope. :(
I will ignore the time spent on gpio toggle for now.  
#155 too, calibration part is most likely to be removed by the compiler. Not sure.

I will try following things: with toggle with redundant test points for #155, this and this+sync correction. 

- [ ] 1. 1 second gpio toggle; oscilloscope should give 0.5 Hz square wave, Since it is a toggle.
- [ ] 2. 10000 millis; 0.05 Hz (will see if doable)
- [ ] 3. 1000 milis; 0.5 Hz
- [ ] 4. 100 millis; 5 Hz 
- [ ] 5. 10 millis; 50 Hz
- [ ] 6. 1 millis; 500Hz
- [ ] 7. 10000 nanos; 50 Hz
- [ ] 8. 1000 nanos; 500 Hz
- [ ] 9. 100 nanos; 5000 Hz
- [ ] 10. 10 nanos; 50000 Hz
- [ ] 11. 1 nanos; 500000 Hz

Note: gpio toggle can consume more than 100 Nanos. However, will test these. 
After these same test with two gpios toggles should give me the time for a single gpio toggle. I will deduct the time in code and retest it all for confirmation.

Any info for sync and suggestion for the testing methodology without an oscilloscope.
:)

**Comment by rahuldeo2047** [comment]
One thing I got that both times start at different times. And that is why both the times are not in sync. If this is so.
I can have a variable in sys_port_init() or in n suitable one as a time offset.
Will that be ok?

**Comment by eerimoq** [comment]
This is what it looks like in the PPC port, something similar should be doable for ESP8266. That is, use the system tick timer registers.

https://github.com/eerimoq/simba/blob/master/src/kernel/ports/ppc/gnu/sys_port.i#L184-L191

**Comment by rahuldeo2047** [comment]
Note: http://www.instructables.com/id/625-Nanosecond-Resolution-Timer-for-Any-Microcontr/

**Pull request closed without merging**
