### PR TITLE
fixed #34 socket_write tcp data more then TCP_SND_BUF

### LINKED ISSUE #34: webserver with large http data is not work
I setup a http server with esp12e, listener give stack 2048, http_connection give stack 8192.
if http response a large http data, like 5KB html page.
then the client can't open the page normal.

is that because socket_write size bigger then TCP_SND_BUF ?

### PR DESCRIPTION
**Pull request by wuwx**

### CODE REVIEW

**Comment by eerimoq** [comment]
Nice job finding out what the problem sending big chunks of data was. Turned out my implementation was naive and needed some improvments.

Before accepting the pull request I had a look in the lwip documentation, especially the sending tcp data section. The ``tcp_sndbuf()`` function shall be used to retrieve the number of available bytes in the output buffer. I think we should read more of the documentation and try to implement this fix as intended by lwip.

The rawapi documentation can be found here (tcp send highlighted): https://github.com/eerimoq/simba/blob/master/3pp/lwip-1.4.1/doc/rawapi.txt#L182-L221

**Comment by wuwx** [comment]
i replace tcp_sndbuf with TCP_MSS/2:)

**Comment by eerimoq** [comment]
I'll test this soon.

**Comment by eerimoq** [comment]
There is still a problem of sending big packets. I added a testcase that writes and reads various buffer sizes to and from a TCP socket. On master it fails as the log below shows, and this pull request fails earlier. I don't have the log unfortunately.

I think the inplementation should be something like this:

Write up to ``tcp_sndbuf()`` bytes of data in ``tcp_send_to()``. Return if all data can be written. If not, suspend the writer thread and send the rest of the data from the ``on_tcp_sent()``. Resume the writing thread when all data has been written to the stack.

```
================================== TEST BEGIN ==================================

app:    wifi_station_espressif_suite-9.0.1 built 2016-10-04 20:29 CEST by erik.
board:  ESP-12E Development Board
mcu:    Espressif ESP8266 @ 80 MHz, 82 kB dram, 4 MB flash

enter: test_init
Connecting to SSID=Qvist
Connected to Access Point (AP). Got IP 192.168.1.103.
exit: test_init: PASSED

enter: test_udp
UDP test
opening socket
binding to 30303
recvfrom
run.py: opening socket
run.py: binding to '':30303
run.py: sending 'hello udp' to ('192.168.1.103', 30303)
run.py: received 'hello udp' from ('192.168.1.103', 30303)
run.py: closing socket
run.py: opening socket
received 'hello udp' from 192.168.1.100:30303
sending 'hello udp' to 192.168.1.100:30303
closing socket
exit: test_udp: PASSED

enter: test_tcp
TCP test
opening listener socket
binding to 40404
listening on 40404
run.py: connecting to 192.168.1.103:40404
run.py: sending 'hello tcp'
run.py: received 'hello tcp'
run.py: closing socket
run.py: opening socket
accepted client 192.168.1.103:40404
read 'hello tcp'
writing 'hello tcp'
closing client socket
closing listener socket
exit: test_tcp: PASSED

enter: test_tcp_sizes
TCP test
opening listener socket
binding to 40405
listening on 40405
run.py: connecting to 192.168.1.103:40405
run.py: sending 1 bytes
run.py: received 1 bytes
run.py: sending 129 bytes
run.py: received 129 bytes
run.py: sending 257 bytes
run.py: received 257 bytes
run.py: sending 385 bytes
run.py: received 385 bytes
run.py: sending 513 bytes
run.py: received 513 bytes
run.py: sending 641 bytes
run.py: received 641 bytes
run.py: sending 769 bytes
run.py: received 769 bytes
run.py: sending 897 bytes
run.py: received 897 bytes
run.py: sending 1025 bytes
run.py: received 1025 bytes
run.py: sending 1153 bytes
run.py: received 1153 bytes
run.py: sending 1281 bytes
run.py: received 1281 bytes
run.py: sending 1409 bytes
run.py: received 1409 bytes
run.py: sending 1537 bytes
run.py: received 1440 bytes
run.py: received 97 bytes
run.py: sending 1665 bytes
run.py: received 1440 bytes
run.py: received 225 bytes
run.py: sending 1793 bytes
run.py: received 1440 bytes
run.py: received 353 bytes
run.py: sending 1921 bytes
run.py: received 1440 bytes
run.py: received 481 bytes
run.py: sending 2049 bytes
run.py: received 1440 bytes
run.py: received 609 bytes
run.py: sending 2177 bytes
run.py: received 1440 bytes
run.py: received 737 bytes
run.py: sending 2305 bytes
run.py: received 1440 bytes
run.py: received 865 bytes
run.py: sending 2433 bytes
run.py: received 1440 bytes
run.py: received 993 bytes
run.py: sending 2561 bytes
run.py: received 1440 bytes
run.py: received 1121 bytes
run.py: sending 2689 bytes
run.py: received 1440 bytes
run.py: received 1249 bytes
run.py: sending 2817 bytes
run.py: received 1440 bytes
run.py: received 1377 bytes
run.py: sending 2945 bytes
```

**Comment by eerimoq** [comment]
I'm about to refactor the socket module and at the same time fix this bug. The plan is to call all lwip-functions from the LwIP thread. This should make the logic simpler and correct.

**Comment by eerimoq** [comment]
I've implemented support for big buffers and pushed it to the repository. I hope it works well for you.

**Pull request closed without merging**
