### PR TITLE
Added support for Arduino Huzzah board

### PR DESCRIPTION
**Pull request by MrSurly**
LED pin works correctly; this is the blue LED on the ESP12 module itself; the Huzzah board also has an LED tied to GPIO0.

### CODE REVIEW

**Comment by eerimoq** [comment]
Looks great!

I pushed the generated documentation file and PlatformIO build script. This board will be included in the next release =)

**Comment by MrSurly** [comment]
Great! Thanks.

Does PIO automatically pull the latest for new projects? Or is it something
you do a PR to PIO for?

**Comment by MrSurly** [comment]
There are two LEDs on the Huzzah board, one on the ESP12 itself (Pin 2), which is blue, and another on the Huzzah board it's attached to.

Looks like I've implemented, `board_pin_string_to_device_index` return 0, which will blink the LED on the Huzzah, while `pin_led_dev` is for pin index 2, which will blink the blue LED.  These should either 1) be the same, or 2) be broken out into two different LEDs?

Throughts?

**Comment by eerimoq** [comment]
PlatformIO will not be affected by the change. I just have to create a new release of Simba that PlatformIO picks up automatically with its package manager. It takes me a few hours to make a proper release, but I might do it in the weekend.

Oops, yeah, I can make the pin mapping function return pin 2 for the led, just as its mapping in board.h.

If you have a good name for the second, Huzzah, LED, feel free to add it as well to board.h and the pin mapping function. The NodeMCU also have two LED:s, but only one defined in the board files as of today. No reason not to add it for completeness, though.

**Comment by MrSurly** [comment]
pin_led2_dev
pin_yellow_led_dev
pin_huzzah_led_dev

Any of these?

**Comment by eerimoq** [comment]
I prefer the first name, pin_led2_dev. It's not the most descriptive name, but looks better to me than the other two. =)

**Comment by MrSurly** [comment]
Agreed.

**Pull request merged**
